version: '3'
services:
  grok:
    image: itzymin/grok:${IMAGE_VERSION}-local
    command: ["npm", "run", "start"]
    container_name: grok
    volumes:
      - ".:/app/:rw"
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      # - "${EXPRESS_HOST_PORT}:${EXPRESS_CONTAINER_PORT}"
      - "3000:3000"
    networks:
      - my-app-network
  mongo: 
    container_name: mongo
    image: mongo
    env_file: .env
    volumes: 
      - mongo-data-volume:/var/lib/mongodb/data
    ports: 
      - '${MONGO_HOST_PORT}:${MONGO_CONTAINER_PORT}'
    networks:
      - my-app-network
#   mongodb:
#     image: postgres:10.0-alpine
#     env_file: .env
#     volumes: 
#       - mongodb-data-volume:/var/lib/mongodb/data
#     ports: 
#       - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
#     networks:
#       - my-app-network
#   redis:
#     image: redis:4.0-alpine
#     env_file: .env
#     volumes:
#       - redis-data-volume:/data
#     ports:
#       - '${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}'
#     networks:
#       - my-app-network

volumes: 
  mongo-data-volume:
#   redis-data-volume:
networks:
  my-app-network: